# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flora < Formula
  desc "Allows to manage and switch between multiple terraform versions"
  homepage "https://github.com/ketchoop/flora"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_darwin_arm64.tar.gz"
      sha256 "5702eb399b5c3e9772145912d40f03b078f89327c7a0824a84d45f49613238a1"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_darwin_amd64.tar.gz"
      sha256 "0e30c40da3361d8c1d095db67a9d18bf316781ecec10270a2e1bb620677bfacb"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_linux_amd64.tar.gz"
      sha256 "8bd9dd6e9cc9dd3ab5b6443fdec82e463942a873e8e4b0fef6dc4de3d0834aae"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_linux_arm64.tar.gz"
      sha256 "e5536d583cf77ec395889d3c4675cea5c31700518a00e49a9b6906ec2289f598"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
  end

  conflicts_with "terraform"

  head "https://github.com/ketchoop/flora.git"

  def caveats
    <<~EOS
      flora --help
    EOS
  end

  test do
    system "#{bin}/flora", "--help"
  end
end
