# This file was generated by GoReleaser. DO NOT EDIT.
class Flora < Formula
  desc "Allows to manage and switch between multiple terraform versions"
  homepage "https://github.com/ketchoop/flora"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ketchoop/flora/releases/download/0.2.0/flora_0.2.0_MacOS_x86_64.tar.gz"
    sha256 "6b7c28c91af2730a80a328fc9579d75ee2b63e8d2f7daab38d8ea03350885a1b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ketchoop/flora/releases/download/0.2.0/flora_0.2.0_Linux_x86_64.tar.gz"
      sha256 "be010728473d60ba7c73e1bdb102fb0a266ac97873da658cdf4d1481f00f0b30"
    end
  end
  
  head "https://github.com/ketchoop/flora.git"

  def install
    bin.install "flora"
  end

  def caveats; <<~EOS
    flora --help
  EOS
  end

  test do
    system "#{bin}/flora", "--help"
  end
end
