# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flora < Formula
  desc "Allows to manage and switch between multiple terraform versions"
  homepage "https://github.com/ketchoop/flora"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_darwin_arm64.tar.gz"
      sha256 "c03db5750f2b6b4b3d53a39e60305c2ceed820cd49fdb3066e0b14e24f775494"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_darwin_amd64.tar.gz"
      sha256 "08f96bdd82886ee30599272a7c0c55331833c63ea41c868aee0e169f31781cc9"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_linux_amd64.tar.gz"
      sha256 "a43ed4f0ae818a670c0de3b4667af921c6e2013944b0cdc97375d9ba487b8e09"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ketchoop/flora/releases/download/0.2.2/flora_0.2.2_linux_arm64.tar.gz"
      sha256 "d7a46511cb0631fff3d444de1f381b0ef0d5cfd0e5720f53cc5eb86008d6c358"

      def install
        case File.basename(ENV["SHELL"])
        when "zsh"
        zsh_completion.install "configs/autocomplete/flora_zsh_autocomplete" => "_flora"
        when "bash"
          url "https://raw.githubusercontent.com/ketchoop/flora/master/configs/autocomplete/flora_bash_autocomplete"
          bash_completion.install "configs/autocomplete/flora_bash_autocomplete" => "_flora"
        end

        bin.install "flora"
      end
    end
  end

  conflicts_with "terraform"

  head "https://github.com/ketchoop/flora.git"

  def caveats
    <<~EOS
      flora --help
    EOS
  end

  test do
    system "#{bin}/flora", "--help"
  end
end
